### ISSUE TITLE
clash api setting点开是空白的

### ISSUE THREAD

**Issue by VIKINGYFY** [muink/homeproxy#1]
浏览器是EDGE，已试过开调试模式清除缓存并硬刷新，还是一样空白的。

![QQ截图20231203155838](https://github.com/muink/homeproxy/assets/7755795/a8fa9b05-36aa-4d51-ac3e-e64a07fc1abe)
![QQ截图20231203155901](https://github.com/muink/homeproxy/assets/7755795/c3f649cf-8924-4a41-b1e6-1c439b68f459)
![QQ截图20231203160014](https://github.com/muink/homeproxy/assets/7755795/5162cdf2-a254-4883-8789-97ccf9209fdb)
![QQ截图20231203160020](https://github.com/muink/homeproxy/assets/7755795/1f1a6b47-bc45-4575-923f-c8691de08ddb)

另外大佬方便写个clash api相关的简易教程吗？比如导入规则什么的，一条一条的添加太不现实了。

谢谢大佬！

**Comment by muink** [comment]
Fixed 3221927ccb5a2d3cf21177fe289ca7949788fc13
