### ISSUE TITLE
在更新订阅时有一个bug

### ISSUE THREAD

**Issue by colahuang8** [muink/homeproxy#10]
这个版本的homeproxy 在更新订阅时有一个bug, 它的机制似乎不是删除原来的站点信息，然后再添加的站点，而是替换改动的部分，其它的保留

这样导致的问题是，如果原先是trojan 结点，带了tls 字段，而这个结点一旦改动成ss 结点，就多出了tls 字段，而报错

希望能修复这个bug, 不然后面就不能自动订阅了，非常麻烦

例如，其中的一个outbound 形如  {
   "type": "shadowsocks",
   "tag": "",
   "routing_mark": 100,
   "server": "",
   "server_port": ...,
   "password": "",
   "method": "aes-128-gcm",
   "tls": {
    "enabled": true,
    "server_name": "...",
    "insecure": false
   }
  },

**Comment by muink** [comment]
这你得向上游反馈
此fork没有修改任何订阅解析的代码

**Comment by colahuang8** [comment]
好的，谢谢
在 2024年8月26日 +0800 18:44，Anya Lin ***@***.***>，写道：
