### ISSUE TITLE
当旁路由使用自定义路由模式时，会强制接管局域网所有的客户机数据？

### ISSUE THREAD

**Issue by nczyw** [muink/homeproxy#11]
我把客户机网关指向主路由，主路由没有科学插件，旁路由，使用自定义路由模式时，客户机的数据被旁路由给抢了？把我客户机给代理了，可以科学上网，请问这是配置问题，还是自定义路由的bug导致的呢？

**Comment by muink** [comment]
设计使然
经过网关的所有常用端口流量都会被代理

**Comment by nczyw** [comment]
> 设计使然 经过网关的所有常用端口流量都会被代理

那这个意思，只要局域网中有homeproxy的旁路由在运行，客户机无论把网关指向谁，都会被旁路由的homeproxy抢过去代理吗？
可是，当我不使用自定义路由模式，比如GFWList模式，旁路由就不会去抢着代理客户机的数据。

**Comment by nczyw** [comment]
因为我测试发现，只有在自定义路由模式时，才会去抢主网关的数据，也就是客户机并没把网关指向旁路由，他却把客户机的数据给代理了。

**Comment by nczyw** [comment]
> 设计使然 经过网关的所有常用端口流量都会被代理

您理解错我的意思了，客户机的网关并没有指向旁路由，旁路由却仍然把客户机的数据给代理了。

**Comment by muink** [comment]
如果客户机的上级网关链路里没有旁路网关
则流量不应该被代理
请检查主路由是否把流量转发到了旁路网关上

另外路由和防火墙相关代码我并未做修改, 如果确认有问题请往上游反馈

**Comment by nczyw** [comment]
> 如果客户机的上级网关链路里没有旁路网关
> 
> 则流量不应该被代理
> 
> 请检查主路由是否把流量转发到了旁路网关上
> 
> 
> 
> 另外路由和防火墙相关代码我并未做修改, 如果确认有问题请往上游反馈

主路由肯定没有转到旁路由的，上一个版本的配置文件，ipk更新到最新版本后，也一直无法启动了，使用的油管七尺雨的配置方法，ruleset规则提示版本不兼容2，上游的homeproxy没有面板，也不能使用选择订阅，我空了，再测试一下上游的homeproxy吧，既然没改，可能旁路由的自定义路由模式也会强制代理客户机数据，刚刚学会配置homeproxy，没想到版本更新后，直接启动不了了。太悲催了。
