### ISSUE TITLE
fakeip如何设置？

### ISSUE THREAD

**Issue by wclmgcd** [muink/homeproxy#5]
用配置文件里：
"fakeip": {
		"enabled": true,
		"inet4_range": "198.18.0.1/15"
		},
		这个是在homeproxy中如何设置？
另外：
{
		"tag": "dns_fakeip",
		"address": "fakeip"
	            },这里是直接--DNS 服务器设置，地址填fakeip，但是出站选什么？只有直连，还有自建的节点

**Comment by muink** [comment]
此项目不支持fakeip, 也不考虑支持fakeip
