### ISSUE TITLE
clash相关功能是准备弃用了吗？

### ISSUE THREAD

**Issue by VIKINGYFY** [muink/homeproxy#6]
clash相关的功能很多有问题，比如面板下载失败等，如果大佬要继续维护的话，可以看一下douglarek大佬的，试用了一下很完善，可惜停更了。
https://github.com/douglarek/luci-app-homeproxy.git

**Comment by muink** [comment]
> clash相关的功能很多有问题

请列举

> 面板下载失败

面板下载失败请考虑是否是自己的网络有问题无法直连 [github](https://github.com/muink/homeproxy/blob/9b89095eacf65fef433976f0ae7b16a70afb3164/root/etc/homeproxy/scripts/update_resources.sh#L77C17-L77C27)
