### ISSUE TITLE
[bug]在 argo 主题下，无法添加新节点

### ISSUE THREAD

**Issue by imken** [muink/homeproxy#9]
### Openwrt版本
[Powered by LuCI openwrt-23.05 branch (git-23.242.12613-a05789f)](https://github.com/openwrt/luci) / [ArgonTheme v2.3.1](https://github.com/jerrykuku/luci-theme-argon) / ImmortalWrt 23.05.3 r27917-81a1f98d5b

### Homeproxy版本
luci-app-homeproxy_git-24.226.23824-9a48dd3_all.ipk

### 问题描述
节点设置 -> 下方输入框输入名称点击“添加”，无法执行。换用bootstrap界面则操作正常：
在argo界面下，此操作的console报错记录如下：
```
node.js?v=git-23.242.12613-a05789f:1374  Uncaught ReferenceError: section is not defined
    at ss.handleAdd (node.js?v=git-23.242.12613-a05789f:1374:54)
    at ClassConstructor.eval (form.js?v=git-23.242.12613-a05789f:150:20)
    at ClassConstructor.eval (ui.js?v=git-23.242.12613-a05789f:359:29)
```

**Comment by muink** [comment]
同样配置无法复现错误
我认为你可以试试清除页面缓存或者开个无痕页面试试

**Comment by imken** [comment]
确实是缓存问题，无痕模式浏览器下正常。不好意思～
